<?php
include("helpCommon.php");
helpHeader();
?>
<H3>Entrada Work Order</H3>
Utilice esta pantalla para meter nuevas work orders.
Este fichero de ayuda explica los campos y como rellenarlos. 
En los campos marcados '**' solo entra si su nivel de 
seguridad es mayor que seclvAddAssignWO,(usualmente 5).

<BR>
<BR>
<H4>Producto</H4>
Seleciona el producto asociado con esta work order.

<H4>Cuenta</H4>
Selecciona la cuenta (si hay alguna) relacionada con esta work order.

<H4>Responsable **</H4>
Seleciona la persona responsable a realizar la work order.

<H4>Fecha Limite **</H4>
El tiempo en que esta workorder deberia estar terminada.El botón
pequeño proximo a este campo muestra un calendario que usted puede
usar para selecionar una fecha. 

<H4>Comienzo Est. **</H4>
La fecha que estima empezar a trabajar en esta work order.
El boton pequeño proximo a este campo muestra un calendario que 
usted pude usar para seleccionar una fecha. 

<H4>Fin Est. **</H4>
La fecha que estima para resolver esta workorder.
El boton pequeño proximo a este campo muestra un calendario que 
usted pude usar para seleccionar una fecha.

<H4>Horas Est. **</H4>
Una estimación de cuánto tiempo llevará resolver la work order.

<H4>Version Informe</H4>
La version del sistema afectado.

<H4>Prioridad **</H4>
Prioridad de la work order.

<H4>Severidad **</H4>
Severidad de la work order. 

<H4>Usuario</H4>
Si hay una persona que deba ser informada de la work order
meter su nombre/organizacion aqui.

<H4>Telefono</H4>
Si tiene un numero de telefono de contacto de 
la persona,meterlo aquí.

<H4>Resumen</H4>
En una linea la descripcion del problema.Lo ideal seria sobre 60 
caracteres,resumir el problema tan concretamente como sea posible.
Un ejemplo está dado aqui para indicar como usarias este campo.
Imagine la siguiente descripcion de un problema.

<pre>
Descripción
El enlace de 'ayuda' en la página 'atraciones siguientes'
(/atraciones/siguientes/index.html)apunta a 
/ayuda/att-upc-ayuda.html,el cual no existe.
</pre>

<UL>
  <LI>Resumen: Problema con una pagina web<BR>
	- este no es un buen resumen.No indica que problema es,
	  en que pagina web es,o que tipo de problema es.</LI>

  <LI>Resumen: Roto el enlace a una pagina web<BR>
	- mejor, en este se indica que problema es,pero 
        todaía no se indica dónde opoque el enlace está roto.</LI>

  <LI>Resumen: El enlace ayuda a atraccione siguiente esta roto<BR>
	- Bien. Ahora sabemos dónde el enlace se ha roto y que 
        es un enlace de ayuda.</LI>

  <LI>Resumen: El enlace a Upc.Att.help esta roto
       (no se encontro /help/att-upc-help.html)<BR>
	-mejor que bien.En este momento sabemos además
       el nombre de el fuichero que no encuenrtra.</LI>

</UL>

<H4>Notas</H4>
Esta seccion es para cualquier informacion sobre la work order 
que no este relatada en la descripcion.
Por ejemplo,For example, 
if you wrote a test harness that automatically raised work orders 
when tests fail, you might put the text:<BR>

<pre>
Generated by automatic test harness v1.2 Started at 11:45:32 23/01/2001
</pre>

<H4>Descripcion</H4>
Aqui es donde relata el problema detalladamente.Incluya 
tanta información como crea relevante.Si sabe
qué necesita para resolver el problema, pongalo aquí;en 
otro caso ponga tanta información como sepa del problema.Como/donde 
ocurre.Puede ser reproducido?A cuantos clientes ha afectado,y como.
Cuantos intentos han sido hechos para resolver el problema.
Que parte del sistema ha sido afectada.

<?php
helpFooter();
?>
